### ISSUE TITLE
Wrong date conversion

### ISSUE THREAD

**Issue by olblak** [chaoss/grimoirelab-kingarthur#31]
```
[2018-05-09 11:28:48,289] - JobListener instence crashed. Error: None is not a valid date
[2018-05-09 11:28:48,290] - Traceback (most recent call last):
  File "/arthur/src/grimoirelab-toolkit/grimoirelab/toolkit/datetime.py", line 165, in unixtime_to_datetime
    dt = datetime.datetime.utcfromtimestamp(ut)
TypeError: a float is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/arthur/.local/lib/python3.5/site-packages/kingarthur-0.1.6-py3.5.egg/arthur/scheduler.py", line 211, in run
    self.listen()
  File "/arthur/.local/lib/python3.5/site-packages/kingarthur-0.1.6-py3.5.egg/arthur/scheduler.py", line 245, in listen
    handler(job)
  File "/arthur/.local/lib/python3.5/site-packages/kingarthur-0.1.6-py3.5.egg/arthur/scheduler.py", line 339, in _handle_successful_job
    from_date = unixtime_to_datetime(result.max_date)
  File "/arthur/src/grimoirelab-toolkit/grimoirelab/toolkit/datetime.py", line 169, in unixtime_to_datetime
    raise InvalidDateError(date=str(ut))
grimoirelab.toolkit.datetime.InvalidDateError: None is not a valid date
```

**Comment by sduenas** [comment]
Which repositories were you analyzing? I need some context to debug the problem. :)

**Comment by olblak** [comment]
Of course :D , I don't know how to get more informations, I am analyzing different sources (git/github/meetup) and I have data for almost all of them.

**Comment by sduenas** [comment]
I found the error. It is caused by those works that don't produce new items. I'll try to fix it as soon as possible.
