### ISSUE TITLE
Error, likely only with Python 3.7

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-kingarthur#46]
When running KingArthur in a Python 3.7 environment, I get:

```
$ arthurd --help
Traceback (most recent call last):
  File "/tmp/install/bin/arthurd", line 35, in <module>
    from arthur.server import ArthurServer
  File "/tmp/install/lib/python3.7/site-packages/arthur/server.py", line 32, in <module>
    from .arthur import Arthur
  File "/tmp/install/lib/python3.7/site-packages/arthur/arthur.py", line 33, in <module>
    from .scheduler import Scheduler
  File "/tmp/install/lib/python3.7/site-packages/arthur/scheduler.py", line 90
    async=self.async_mode)  # noqa: W606
        ^
SyntaxError: invalid syntax
```

Maybe this is due to some problem specific to Python 3.7 ?

**Comment by valeriocos** [comment]
This PR should fix this issue:
https://github.com/chaoss/grimoirelab-kingarthur/pull/45, but the pip package doesn't include it.

**Comment by jjmerchante** [comment]
Python 3.7 reached its end of life. Closing this issue.
